# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: use-mirror-repository

on:
  workflow_call:
    inputs:
      GIT_TARGET_SERVER:  # required
        required: true
        type: string
      GIT_TARGET_REPO:    # required
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:    # required
        required: true

jobs:
  mirror-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Print Contexts/Inputs/Secrets
        run: |
          echo "[Contexts]"
          echo "[Inputs]"
          echo "inputs.GIT_TARGET_SERVER = ${{ inputs.GIT_TARGET_SERVER }}"
          echo "inputs.GIT_TARGET_REPO = ${{ inputs.GIT_TARGET_REPO }}"
          echo "[Secrets]"
          echo "secrets.SSH_PRIVATE_KEY = ${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: 'recursive'
          fetch-depth: 0  # 0 indicates all history for all branches and tags.

      - name: Mirror to '${{ inputs.GIT_TARGET_SERVER }}'
        # https://github.com/pixta-dev/repository-mirroring-action/issues/34#issuecomment-2639288050
        uses: fscarmen/repository-mirroring-action@v1.0.0
        # uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: git@${{ inputs.GIT_TARGET_SERVER }}:${{ inputs.GIT_TARGET_REPO }}.git
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
